# Generated by Django 5.2.16 on 2026-07-28 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('crawler', 'Crawler'), ('rss', 'RSS Feed'), ('manual_url', 'Input URL Manual'), ('manual_article', 'Input Artikel Manual')], db_index=True, default='crawler', max_length=30)),
                ('crawler_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('running', 'Sedang Berjalan'), ('completed', 'Selesai'), ('completed_with_errors', 'Selesai dengan Kesalahan'), ('failed', 'Gagal'), ('cancelled', 'Dibatalkan')], db_index=True, default='pending', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('total_created', models.PositiveIntegerField(default=0)),
                ('total_duplicate', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('trigger_type', models.CharField(default='system', help_text='Contoh: system, schedule, user, atau management_command.', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_jobs', to='sources.source')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_collection_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=1000)),
                ('normalized_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('found', 'Ditemukan'), ('created', 'Dibuat'), ('duplicate', 'Duplikat'), ('rejected', 'Ditolak'), ('failed', 'Gagal')], db_index=True, default='found', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='articles.article')),
                ('collection_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collection.collectionjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collectionjob',
            index=models.Index(fields=['source', 'status', 'created_at'], name='colljob_src_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionjob',
            index=models.Index(fields=['job_type', 'created_at'], name='colljob_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionjobitem',
            index=models.Index(fields=['collection_job', 'status'], name='collitem_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionjobitem',
            index=models.Index(fields=['normalized_url'], name='collitem_norm_url_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionjobitem',
            constraint=models.UniqueConstraint(fields=('collection_job', 'original_url'), name='unique_collection_job_url'),
        ),
    ]
