-- MedIntel Source Seed - compatible with sources.0002
-- Run migrations first, then import this file.
BEGIN;

INSERT INTO public.sources_source (
    name,
    code,
    domain,
    base_url,
    source_type,
    is_verified,
    is_active,
    verification_notes,
    verified_at,
    created_at,
    updated_at,
    allow_subdomains,
    crawl_enabled,
    crawl_strategy,
    crawler_notes,
    last_crawled_at,
    max_articles_per_run,
    request_delay_seconds,
    request_timeout_seconds,
    user_agent
)
VALUES
('Kementerian Kesehatan RI', 'kemkes', 'kemkes.go.id', 'https://kemkes.go.id', 'government', TRUE, TRUE, 'Tier A1. Situs resmi Kementerian Kesehatan RI; sumber primer nasional.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Ayo Sehat Kemenkes', 'ayo-sehat', 'ayosehat.kemkes.go.id', 'https://ayosehat.kemkes.go.id', 'government', TRUE, TRUE, 'Tier A1. Portal resmi edukasi kesehatan Kementerian Kesehatan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('BKPK Kemenkes', 'bkpk-kemkes', 'badankebijakan.kemkes.go.id', 'https://badankebijakan.kemkes.go.id', 'government', TRUE, TRUE, 'Tier A1. Situs resmi Badan Kebijakan Pembangunan Kesehatan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('SATUSEHAT', 'satusehat', 'satusehat.kemkes.go.id', 'https://satusehat.kemkes.go.id', 'government', TRUE, TRUE, 'Tier A1. Platform resmi Kementerian Kesehatan; lebih sesuai untuk kebijakan dan ekosistem data.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Badan POM RI', 'bpom', 'pom.go.id', 'https://www.pom.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber primer keamanan obat, pangan, kontaminasi, dan penarikan produk.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kementerian Pertanian RI', 'kementan', 'pertanian.go.id', 'https://pertanian.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi pertanian, pangan, kesehatan hewan, dan zoonosis.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Ditjen Peternakan dan Kesehatan Hewan', 'ditjen-pkh', 'ditjenpkh.pertanian.go.id', 'https://ditjenpkh.pertanian.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber primer penyakit hewan strategis dan zoonosis.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Badan Karantina Indonesia', 'karantina-indonesia', 'karantinaindonesia.go.id', 'https://karantinaindonesia.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi ancaman penyakit lintas batas dan karantina.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('BNPB', 'bnpb', 'bnpb.go.id', 'https://bnpb.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi bencana dan konteks risiko kesehatan masyarakat.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('BMKG', 'bmkg', 'bmkg.go.id', 'https://www.bmkg.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi cuaca, iklim, banjir, dan faktor lingkungan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Badan Pusat Statistik', 'bps', 'bps.go.id', 'https://www.bps.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi data populasi dan konteks wilayah.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Satu Data Indonesia', 'satu-data-indonesia', 'data.go.id', 'https://data.go.id', 'government', TRUE, TRUE, 'Tier A1. Portal resmi data pemerintah.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kementerian Lingkungan Hidup dan Kehutanan', 'klhk', 'menlhk.go.id', 'https://www.menlhk.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi lingkungan, pencemaran, dan kualitas ekosistem.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('BRIN', 'brin', 'brin.go.id', 'https://brin.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi riset nasional.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kementerian Luar Negeri RI', 'kemlu', 'kemlu.go.id', 'https://kemlu.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi isu luar negeri dan perlindungan WNI.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kementerian Perhubungan RI', 'kemenhub', 'kemenhub.go.id', 'https://dephub.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi transportasi dan pintu masuk.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Direktorat Jenderal Imigrasi', 'imigrasi', 'imigrasi.go.id', 'https://www.imigrasi.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi kebijakan perjalanan dan perlintasan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kementerian Komunikasi dan Digital', 'komdigi', 'komdigi.go.id', 'https://www.komdigi.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi klarifikasi informasi dan komunikasi publik.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Polri', 'polri', 'polri.go.id', 'https://polri.go.id', 'government', TRUE, TRUE, 'Tier A1. Sumber resmi insiden, penegakan hukum, pangan ilegal, dan keracunan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('World Health Organization', 'who', 'who.int', 'https://www.who.int', 'international_media', TRUE, TRUE, 'Tier A2. Organisasi kesehatan internasional resmi; gunakan URL pattern untuk Indonesia, SEARO, dan Disease Outbreak News.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('World Organisation for Animal Health', 'woah', 'woah.org', 'https://www.woah.org', 'international_media', TRUE, TRUE, 'Tier A2. Organisasi resmi penyakit hewan dan zoonosis.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Food and Agriculture Organization', 'fao', 'fao.org', 'https://www.fao.org', 'international_media', TRUE, TRUE, 'Tier A2. Organisasi resmi pangan, pertanian, dan zoonosis.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('UNICEF Indonesia', 'unicef-indonesia', 'unicef.org', 'https://www.unicef.org/indonesia', 'international_media', TRUE, TRUE, 'Tier A2. Organisasi internasional resmi; fokus kesehatan anak, imunisasi, gizi, dan sanitasi.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('ReliefWeb', 'reliefweb', 'reliefweb.int', 'https://reliefweb.int', 'international_media', TRUE, TRUE, 'Tier A2. Portal kemanusiaan resmi; selalu simpan dan evaluasi sumber asal artikel.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('US CDC', 'cdc-us', 'cdc.gov', 'https://www.cdc.gov', 'international_media', TRUE, TRUE, 'Tier A2. Instansi kesehatan publik resmi Amerika Serikat.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('ECDC', 'ecdc', 'ecdc.europa.eu', 'https://www.ecdc.europa.eu', 'international_media', TRUE, TRUE, 'Tier A2. Instansi kesehatan publik resmi Uni Eropa.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Africa CDC', 'africa-cdc', 'africacdc.org', 'https://africacdc.org', 'international_media', TRUE, TRUE, 'Tier A2. Instansi kesehatan publik regional Afrika.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('UK Health Security Agency', 'ukhsa', 'gov.uk', 'https://www.gov.uk/government/organisations/uk-health-security-agency', 'international_media', TRUE, TRUE, 'Tier A2. Instansi kesehatan publik resmi Inggris; gunakan URL pattern khusus UKHSA.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('ProMED', 'promed', 'promedmail.org', 'https://promedmail.org', 'international_media', TRUE, TRUE, 'Tier B1. Jaringan early warning penyakit; laporan awal wajib dikonfirmasi silang.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('GISAID', 'gisaid', 'gisaid.org', 'https://gisaid.org', 'international_media', TRUE, FALSE, 'Tier A2. Referensi genomik; crawling dinonaktifkan karena akses dan ketentuan penggunaan perlu ditinjau.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Our World in Data', 'owid', 'ourworldindata.org', 'https://ourworldindata.org', 'international_media', TRUE, FALSE, 'Tier B2. Sumber data sekunder untuk konteks, bukan pembentuk sinyal lokal utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('ANTARA News', 'antara', 'antaranews.com', 'https://www.antaranews.com', 'national_media', TRUE, TRUE, 'Tier B1. Kantor berita nasional; prioritas tinggi.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kompas.com', 'kompas', 'kompas.com', 'https://www.kompas.com', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tempo.co', 'tempo', 'tempo.co', 'https://www.tempo.co', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('CNN Indonesia', 'cnn-indonesia', 'cnnindonesia.com', 'https://www.cnnindonesia.com', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Detikcom', 'detik', 'detik.com', 'https://www.detik.com', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama; gunakan URL pattern kanal berita dan kesehatan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Liputan6', 'liputan6', 'liputan6.com', 'https://www.liputan6.com', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribunnews', 'tribunnews', 'tribunnews.com', 'https://www.tribunnews.com', 'national_media', TRUE, TRUE, 'Tier B1. Jaringan media nasional dan lokal.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Media Indonesia', 'media-indonesia', 'mediaindonesia.com', 'https://mediaindonesia.com', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Metro TV News', 'metrotvnews', 'metrotvnews.com', 'https://www.metrotvnews.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi administratif/faktual dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('BeritaSatu', 'beritasatu', 'beritasatu.com', 'https://www.beritasatu.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi administratif/faktual dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('SINDOnews', 'sindonews', 'sindonews.com', 'https://www.sindonews.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi administratif/faktual dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Okezone', 'okezone', 'okezone.com', 'https://www.okezone.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi administratif/faktual dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kumparan', 'kumparan', 'kumparan.com', 'https://kumparan.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi administratif/faktual dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Suara.com', 'suara', 'suara.com', 'https://www.suara.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi administratif/faktual dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Republika', 'republika', 'republika.co.id', 'https://republika.co.id', 'national_media', TRUE, TRUE, 'Tier B1. Media nasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Jawa Pos', 'jawa-pos', 'jawapos.com', 'https://www.jawapos.com', 'national_media', TRUE, TRUE, 'Tier B1. Jaringan media nasional dan lokal.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Jakarta Post', 'jakarta-post', 'thejakartapost.com', 'https://www.thejakartapost.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Uji akses/paywall dan verifikasi sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Jakarta Globe', 'jakarta-globe', 'jakartaglobe.id', 'https://jakartaglobe.id', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Katadata', 'katadata', 'katadata.co.id', 'https://katadata.co.id', 'national_media', TRUE, TRUE, 'Tier B1. Media data dan kebijakan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kontan', 'kontan', 'kontan.co.id', 'https://www.kontan.co.id', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Fokus dampak ekonomi dan industri kesehatan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Bisnis Indonesia', 'bisnis-indonesia', 'bisnis.com', 'https://www.bisnis.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Fokus dampak ekonomi dan industri kesehatan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('CNBC Indonesia', 'cnbc-indonesia', 'cnbcindonesia.com', 'https://www.cnbcindonesia.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Fokus dampak ekonomi dan kebijakan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('VOA Indonesia', 'voa-indonesia', 'voaindonesia.com', 'https://www.voaindonesia.com', 'national_media', TRUE, TRUE, 'Tier B1. Media internasional berbahasa Indonesia.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('RRI', 'rri', 'rri.co.id', 'https://rri.co.id', 'national_media', TRUE, TRUE, 'Tier B1. Media publik nasional dan daerah.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('TVRI', 'tvri', 'tvri.go.id', 'https://tvri.go.id', 'national_media', TRUE, TRUE, 'Tier B1. Media publik nasional.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Merdeka.com', 'merdeka', 'merdeka.com', 'https://www.merdeka.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('VIVA', 'viva', 'viva.co.id', 'https://www.viva.co.id', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('IDN Times', 'idn-times', 'idntimes.com', 'https://www.idntimes.com', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Verifikasi dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Narasi', 'narasi', 'narasi.tv', 'https://narasi.tv', 'national_media', FALSE, FALSE, 'Tier B1 kandidat. Lebih sesuai untuk konteks kebijakan dan sosial.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Conversation Indonesia', 'conversation-id', 'theconversation.com', 'https://theconversation.com/id', 'national_media', TRUE, FALSE, 'Tier B2. Analisis akademik; tidak dijadikan pembentuk sinyal kejadian awal utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Detik Health', 'detik-health', 'health.detik.com', 'https://health.detik.com', 'national_media', TRUE, TRUE, 'Tier B2. Kanal kesehatan aktual.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kompas Health', 'kompas-health', 'health.kompas.com', 'https://health.kompas.com', 'national_media', TRUE, TRUE, 'Tier B2. Kanal kesehatan aktual.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Liputan6 Health', 'liputan6-health', 'health.liputan6.com', 'https://www.liputan6.com/health', 'national_media', TRUE, TRUE, 'Tier B2. Kanal kesehatan aktual.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Halodoc', 'halodoc', 'halodoc.com', 'https://www.halodoc.com', 'other', FALSE, FALSE, 'Tier B2 kandidat. Portal edukasi; gunakan hanya sebagai pengayaan, bukan sumber sinyal utama.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Alodokter', 'alodokter', 'alodokter.com', 'https://www.alodokter.com', 'other', FALSE, FALSE, 'Tier B2 kandidat. Portal edukasi; gunakan hanya sebagai pengayaan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('KlikDokter', 'klikdokter', 'klikdokter.com', 'https://www.klikdokter.com', 'other', FALSE, FALSE, 'Tier B2 kandidat. Portal edukasi; gunakan hanya sebagai pengayaan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Hello Sehat', 'hello-sehat', 'hellosehat.com', 'https://hellosehat.com', 'other', FALSE, FALSE, 'Tier B2 kandidat. Portal edukasi; gunakan hanya sebagai pengayaan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('National Geographic Indonesia', 'natgeo-id', 'nationalgeographic.grid.id', 'https://nationalgeographic.grid.id', 'other', FALSE, FALSE, 'Tier B2 kandidat. Sains, lingkungan, dan zoonosis.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Mongabay Indonesia', 'mongabay-id', 'mongabay.co.id', 'https://www.mongabay.co.id', 'other', TRUE, TRUE, 'Tier B2. Lingkungan, satwa, dan zoonosis.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Serambi Indonesia', 'serambi-indonesia', 'serambinews.com', 'https://serambinews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Aceh; verifikasi Dewan Pers dan uji crawler sebelum aktivasi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Aceh', 'tribun-aceh', 'aceh.tribunnews.com', 'https://aceh.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Aceh.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Waspada', 'waspada', 'waspada.co.id', 'https://waspada.co.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Medan', 'tribun-medan', 'medan.tribunnews.com', 'https://medan.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Analisa Daily', 'analisa-daily', 'analisadaily.com', 'https://analisadaily.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Padang Ekspres', 'padang-ekspres', 'padek.jawapos.com', 'https://padek.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Barat.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Harian Singgalang', 'harian-singgalang', 'hariansinggalang.co.id', 'https://hariansinggalang.co.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Barat.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Riau Pos', 'riau-pos', 'riaupos.jawapos.com', 'https://riaupos.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Riau.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Pekanbaru', 'tribun-pekanbaru', 'pekanbaru.tribunnews.com', 'https://pekanbaru.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Riau.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Jambi', 'tribun-jambi', 'jambi.tribunnews.com', 'https://jambi.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Jambi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Sumatera Ekspres', 'sumatera-ekspres', 'sumeks.co', 'https://sumeks.co', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Selatan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Sumsel', 'tribun-sumsel', 'palembang.tribunnews.com', 'https://palembang.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sumatera Selatan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Bengkulu Ekspress', 'bengkulu-ekspress', 'bengkuluekspress.disway.id', 'https://bengkuluekspress.disway.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bengkulu.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Lampung', 'tribun-lampung', 'lampung.tribunnews.com', 'https://lampung.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Lampung.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Lampung', 'radar-lampung', 'radarlampung.disway.id', 'https://radarlampung.disway.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Lampung.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Bangka Pos', 'bangka-pos', 'babel.tribunnews.com', 'https://babel.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bangka Belitung.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Warta Kota', 'warta-kota', 'wartakota.tribunnews.com', 'https://wartakota.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Jabodetabek.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Bogor', 'radar-bogor', 'radarbogor.jawapos.com', 'https://radarbogor.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bogor.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Pikiran Rakyat', 'pikiran-rakyat', 'pikiran-rakyat.com', 'https://www.pikiran-rakyat.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Jawa Barat.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Jabar', 'tribun-jabar', 'jabar.tribunnews.com', 'https://jabar.tribunnews.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Jawa Barat.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kompas Bandung', 'kompas-bandung', 'bandung.kompas.com', 'https://bandung.kompas.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Bandung.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Bandung', 'radar-bandung', 'radarbandung.id', 'https://www.radarbandung.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bandung.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Ayo Bandung', 'ayo-bandung', 'ayobandung.com', 'https://www.ayobandung.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bandung.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Suara Merdeka', 'suara-merdeka', 'suaramerdeka.com', 'https://www.suaramerdeka.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Jawa Tengah.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Jateng', 'tribun-jateng', 'jateng.tribunnews.com', 'https://jateng.tribunnews.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Jawa Tengah.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Solo', 'radar-solo', 'radarsolo.jawapos.com', 'https://radarsolo.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Solo.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Semarang', 'radar-semarang', 'radarsemarang.jawapos.com', 'https://radarsemarang.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Semarang.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Jogja', 'tribun-jogja', 'jogja.tribunnews.com', 'https://jogja.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat DI Yogyakarta.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kedaulatan Rakyat', 'kedaulatan-rakyat', 'krjogja.com', 'https://www.krjogja.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat DI Yogyakarta.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Harian Jogja', 'harian-jogja', 'harianjogja.com', 'https://www.harianjogja.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat DI Yogyakarta.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Surya', 'surya', 'surya.co.id', 'https://surya.co.id', 'local_media', TRUE, TRUE, 'Tier C1 pilot Jawa Timur.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Jatim', 'tribun-jatim', 'jatim.tribunnews.com', 'https://jatim.tribunnews.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Jawa Timur.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Surabaya', 'radar-surabaya', 'radarsurabaya.jawapos.com', 'https://radarsurabaya.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Surabaya.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Malang Times', 'malang-times', 'malangtimes.com', 'https://www.malangtimes.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Malang.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Times Indonesia', 'times-indonesia', 'timesindonesia.co.id', 'https://timesindonesia.co.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat jaringan daerah.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Banten', 'radar-banten', 'radarbanten.co.id', 'https://www.radarbanten.co.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Banten.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Bali Post', 'bali-post', 'balipost.com', 'https://www.balipost.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Bali.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Bali', 'tribun-bali', 'bali.tribunnews.com', 'https://bali.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bali.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Bali', 'radar-bali', 'radarbali.jawapos.com', 'https://radarbali.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Bali.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Lombok Post', 'lombok-post', 'lombokpost.jawapos.com', 'https://lombokpost.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat NTB.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Lombok', 'tribun-lombok', 'ntb.tribunnews.com', 'https://ntb.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat NTB.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Victory News', 'victory-news', 'victorynews.id', 'https://www.victorynews.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat NTT.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Pos Kupang', 'pos-kupang', 'kupang.tribunnews.com', 'https://kupang.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat NTT.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Pontianak Post', 'pontianak-post', 'pontianakpost.jawapos.com', 'https://pontianakpost.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Barat.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Pontianak', 'tribun-pontianak', 'pontianak.tribunnews.com', 'https://pontianak.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Barat.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kalteng Pos', 'kalteng-pos', 'kaltengpos.jawapos.com', 'https://kaltengpos.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Tengah.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Banjarmasin Post', 'banjarmasin-post', 'banjarmasin.tribunnews.com', 'https://banjarmasin.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Selatan.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kaltim Post', 'kaltim-post', 'kaltimpost.jawapos.com', 'https://kaltimpost.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Timur.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Kaltim', 'tribun-kaltim', 'kaltim.tribunnews.com', 'https://kaltim.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Timur.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Tarakan', 'radar-tarakan', 'radartarakan.jawapos.com', 'https://radartarakan.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Kalimantan Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Fajar', 'fajar', 'fajaronline.co.id', 'https://fajaronline.co.id', 'local_media', TRUE, TRUE, 'Tier C1 pilot Sulawesi Selatan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Timur', 'tribun-timur', 'makassar.tribunnews.com', 'https://makassar.tribunnews.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Sulawesi Selatan.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Manado', 'tribun-manado', 'manado.tribunnews.com', 'https://manado.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sulawesi Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Manado Post', 'manado-post', 'manadopost.jawapos.com', 'https://manadopost.jawapos.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sulawesi Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Gorontalo', 'tribun-gorontalo', 'gorontalo.tribunnews.com', 'https://gorontalo.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Gorontalo.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Radar Sulteng', 'radar-sulteng', 'radarsulteng.id', 'https://radarsulteng.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sulawesi Tengah.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Kendari Pos', 'kendari-pos', 'kendaripos.fajar.co.id', 'https://kendaripos.fajar.co.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sulawesi Tenggara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Sultra', 'tribun-sultra', 'sultra.tribunnews.com', 'https://sultra.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Sulawesi Tenggara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Ambon', 'tribun-ambon', 'ambon.tribunnews.com', 'https://ambon.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Maluku.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Siwalima', 'siwalima', 'siwalimanews.com', 'https://siwalimanews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Maluku.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Malut Post', 'malut-post', 'malutpost.id', 'https://malutpost.id', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Maluku Utara.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Cenderawasih Pos', 'cenderawasih-pos', 'ceposonline.com', 'https://www.ceposonline.com', 'local_media', TRUE, TRUE, 'Tier C1 pilot Papua.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Tribun Papua', 'tribun-papua', 'papua.tribunnews.com', 'https://papua.tribunnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Papua.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Sorong News', 'sorong-news', 'sorongnews.com', 'https://sorongnews.com', 'local_media', FALSE, FALSE, 'Tier C1 kandidat Papua Barat Daya.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Reuters', 'reuters', 'reuters.com', 'https://www.reuters.com', 'international_media', TRUE, TRUE, 'Tier B1. Kantor berita internasional; uji robots, paywall, dan struktur halaman.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Associated Press', 'associated-press', 'apnews.com', 'https://apnews.com', 'international_media', TRUE, TRUE, 'Tier B1. Kantor berita internasional.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('BBC', 'bbc', 'bbc.com', 'https://www.bbc.com', 'international_media', TRUE, TRUE, 'Tier B1. Media internasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Al Jazeera', 'al-jazeera', 'aljazeera.com', 'https://www.aljazeera.com', 'international_media', TRUE, TRUE, 'Tier B1. Media internasional utama.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Channel News Asia', 'cna', 'channelnewsasia.com', 'https://www.channelnewsasia.com', 'international_media', TRUE, TRUE, 'Tier B1. Media regional Asia Tenggara.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Straits Times', 'straits-times', 'straitstimes.com', 'https://www.straitstimes.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat. Uji paywall dan akses crawling.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('South China Morning Post', 'scmp', 'scmp.com', 'https://www.scmp.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat. Uji paywall dan akses crawling.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('ABC Australia', 'abc-australia', 'abc.net.au', 'https://www.abc.net.au', 'international_media', TRUE, TRUE, 'Tier B1. Media publik Australia.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Guardian', 'guardian', 'theguardian.com', 'https://www.theguardian.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat. Uji struktur dan relevansi.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('France 24', 'france24', 'france24.com', 'https://www.france24.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Deutsche Welle', 'dw', 'dw.com', 'https://www.dw.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('NHK', 'nhk', 'nhk.or.jp', 'https://www3.nhk.or.jp/nhkworld', 'international_media', TRUE, TRUE, 'Tier B1. Media publik Jepang.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Japan Times', 'japan-times', 'japantimes.co.jp', 'https://www.japantimes.co.jp', 'international_media', FALSE, FALSE, 'Tier B1 kandidat. Uji paywall.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Bangkok Post', 'bangkok-post', 'bangkokpost.com', 'https://www.bangkokpost.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat Thailand.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Bernama', 'bernama', 'bernama.com', 'https://www.bernama.com', 'international_media', TRUE, TRUE, 'Tier B1. Kantor berita Malaysia.', NOW(), NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Star Malaysia', 'the-star-my', 'thestar.com.my', 'https://www.thestar.com.my', 'international_media', FALSE, FALSE, 'Tier B1 kandidat Malaysia.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Rappler', 'rappler', 'rappler.com', 'https://www.rappler.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat Filipina.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('Philippine Daily Inquirer', 'inquirer-ph', 'inquirer.net', 'https://www.inquirer.net', 'international_media', FALSE, FALSE, 'Tier B1 kandidat Filipina.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('VNExpress', 'vnexpress', 'vnexpress.net', 'https://vnexpress.net', 'international_media', FALSE, FALSE, 'Tier B1 kandidat Vietnam.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, ''),
('The Hindu', 'the-hindu', 'thehindu.com', 'https://www.thehindu.com', 'international_media', FALSE, FALSE, 'Tier B1 kandidat India.', NULL, NOW(), NOW(), FALSE, FALSE, 'html', '', NULL, 50, 1.0, 20, '')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    domain = EXCLUDED.domain,
    base_url = EXCLUDED.base_url,
    source_type = EXCLUDED.source_type,
    is_verified = EXCLUDED.is_verified,
    is_active = EXCLUDED.is_active,
    verification_notes = EXCLUDED.verification_notes,
    verified_at = EXCLUDED.verified_at,
    allow_subdomains = EXCLUDED.allow_subdomains,
    crawl_enabled = EXCLUDED.crawl_enabled,
    crawl_strategy = EXCLUDED.crawl_strategy,
    crawler_notes = EXCLUDED.crawler_notes,
    last_crawled_at = EXCLUDED.last_crawled_at,
    max_articles_per_run = EXCLUDED.max_articles_per_run,
    request_delay_seconds = EXCLUDED.request_delay_seconds,
    request_timeout_seconds = EXCLUDED.request_timeout_seconds,
    user_agent = EXCLUDED.user_agent,
    updated_at = NOW();

COMMIT;

-- Verification:
-- SELECT COUNT(*) FROM public.sources_source;
