# Generated by Django 5.2.16 on 2026-07-28 09:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_diseases_article_locations'),
        ('entities', '0003_articledisease_validation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('epidemiological', 'Epidemiologis'), ('geographic', 'Geografis'), ('impact', 'Dampak'), ('response', 'Respons'), ('information', 'Informasi'), ('anomaly', 'Anomali')], db_index=True, max_length=30)),
                ('default_weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('requires_analyst_validation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(choices=[('increasing', 'Meningkat'), ('decreasing', 'Menurun'), ('stable', 'Stabil'), ('spreading', 'Meluas'), ('new', 'Baru'), ('unknown', 'Belum Diketahui')], db_index=True, default='unknown', max_length=20)),
                ('summary', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, help_text='Keyakinan teknis sistem terhadap pembentukan indikator.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('detected', 'Terdeteksi'), ('needs_review', 'Perlu Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak')], db_index=True, default='needs_review', max_length=20)),
                ('created_by_system', models.BooleanField(default=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='entities.disease')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='entities.location')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_indicators', to=settings.AUTH_USER_MODEL)),
                ('indicator_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.indicatortype')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_primary_evidence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_evidences', to='articles.article')),
                ('article_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_evidences', to='entities.articlefact')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='indicators.indicator')),
            ],
            options={
                'ordering': ['-is_primary_evidence', 'created_at'],
                'indexes': [models.Index(fields=['indicator', 'is_primary_evidence'], name='indicator_evidence_primary_idx')],
                'constraints': [models.UniqueConstraint(fields=('indicator', 'article_fact'), name='unique_indicator_article_fact')],
            },
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['indicator_type', 'status', 'event_date'], name='indicator_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['disease', 'location', 'event_date'], name='indicator_dis_loc_idx'),
        ),
    ]
