# Generated by Django 5.2.16 on 2026-07-28 14:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_diseases_article_locations'),
        ('entities', '0003_articledisease_validation_notes_and_more'),
        ('indicators', '0002_indicatorreviewlog'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('event_start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('needs_review', 'Perlu Ditinjau'), ('under_review', 'Sedang Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak'), ('escalated', 'Dieskalasi'), ('closed', 'Ditutup')], db_index=True, default='needs_review', max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], db_index=True, default='medium', max_length=20)),
                ('confidence_level', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('unassessed', 'Belum Dinilai')], db_index=True, default='unassessed', max_length=20)),
                ('system_score', models.FloatField(blank=True, help_text='Skor teknis awal pembentukan sinyal.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_by_system', models.BooleanField(default=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_signals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signals', to=settings.AUTH_USER_MODEL)),
                ('primary_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_signals', to='entities.disease')),
                ('primary_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_signals', to='entities.location')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_level', '-last_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('primary', 'Sumber Utama'), ('supporting', 'Sumber Pendukung'), ('corroborating', 'Sumber Penguat'), ('contradicting', 'Sumber Bertentangan')], db_index=True, default='supporting', max_length=20)),
                ('relevance_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_primary_source', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_signal_articles', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_links', to='articles.article')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_articles', to='signals.signal')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='signals', through='signals.SignalArticle', to='articles.article'),
        ),
        migrations.CreateModel(
            name='SignalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_links', to='entities.disease')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_diseases', to='signals.signal')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='signals', through='signals.SignalDisease', to='entities.disease'),
        ),
        migrations.CreateModel(
            name='SignalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draf'), ('needs_review', 'Perlu Ditinjau'), ('under_review', 'Sedang Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak'), ('escalated', 'Dieskalasi'), ('closed', 'Ditutup')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draf'), ('needs_review', 'Perlu Ditinjau'), ('under_review', 'Sedang Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak'), ('escalated', 'Dieskalasi'), ('closed', 'Ditutup')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='signals.signal')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_primary', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_signal_indicators', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_links', to='indicators.indicator')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_indicators', to='signals.signal')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='signals', through='signals.SignalIndicator', to='indicators.indicator'),
        ),
        migrations.CreateModel(
            name='SignalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_links', to='entities.location')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_locations', to='signals.signal')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='signals', through='signals.SignalLocation', to='entities.location'),
        ),
        migrations.CreateModel(
            name='SignalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('relevance_reason', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_links', to='requirements.intelligencerequirement')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_requirements', to='signals.signal')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='signals', through='signals.SignalRequirement', to='requirements.intelligencerequirement'),
        ),
        migrations.AddConstraint(
            model_name='signalarticle',
            constraint=models.UniqueConstraint(fields=('signal', 'article'), name='unique_signal_article'),
        ),
        migrations.AddConstraint(
            model_name='signaldisease',
            constraint=models.UniqueConstraint(fields=('signal', 'disease'), name='unique_signal_disease'),
        ),
        migrations.AddIndex(
            model_name='signalhistory',
            index=models.Index(fields=['signal', 'changed_at'], name='signalhistory_signal_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalindicator',
            constraint=models.UniqueConstraint(fields=('signal', 'indicator'), name='unique_signal_indicator'),
        ),
        migrations.AddConstraint(
            model_name='signallocation',
            constraint=models.UniqueConstraint(fields=('signal', 'location'), name='unique_signal_location'),
        ),
        migrations.AddConstraint(
            model_name='signalrequirement',
            constraint=models.UniqueConstraint(fields=('signal', 'requirement'), name='unique_signal_requirement'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['status', 'priority_level', 'last_updated_at'], name='signal_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['primary_disease', 'primary_location', 'event_start_date'], name='signal_dis_loc_date_idx'),
        ),
    ]
