# Generated by Django 5.2.16 on 2026-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='analyst_judgement',
            field=models.TextField(blank=True, help_text='Penilaian atau judgement awal analis terhadap sinyal.'),
        ),
        migrations.AddField(
            model_name='signal',
            name='implication',
            field=models.TextField(blank=True, help_text='Implikasi yang mungkin timbul dari sinyal.'),
        ),
        migrations.AddField(
            model_name='signal',
            name='information_gaps',
            field=models.TextField(blank=True, help_text='Informasi yang masih belum tersedia atau perlu diverifikasi.'),
        ),
        migrations.AddField(
            model_name='signal',
            name='recommended_action',
            field=models.TextField(blank=True, help_text='Rekomendasi tindak lanjut awal.'),
        ),
    ]
