# Generated by Django 5.2.16 on 2026-08-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_location_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='classification_basis',
            field=models.TextField(blank=True, help_text='Bukti epidemiologis yang mendasari klasifikasi kejadian.'),
        ),
        migrations.AddField(
            model_name='signal',
            name='event_classification',
            field=models.CharField(choices=[('undetermined', 'Belum ditentukan'), ('routine', 'Endemik / rutin'), ('emerging', 'Emerging'), ('re_emerging', 'Re-emerging'), ('unknown_cluster', 'Klaster belum diketahui')], db_index=True, default='undetermined', help_text='Klasifikasi kejadian pada lokasi dan periode sinyal; bukan atribut permanen penyakit.', max_length=30),
        ),
    ]
