# Generated by Django 5.2.16 on 2026-08-09 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('evaluation_type', models.CharField(choices=[('expert', 'Validasi Ahli'), ('uat', 'User Acceptance Test')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('completed', 'Selesai')], db_index=True, default='draft', max_length=20)),
                ('evaluator_name', models.CharField(max_length=255)),
                ('evaluator_role', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('evaluation_date', models.DateField(db_index=True)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('criterion_notes', models.JSONField(blank=True, default=dict)),
                ('task_results', models.JSONField(blank=True, default=dict)),
                ('general_findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_quality_evaluations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quality_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evaluation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Dibuat'), ('updated', 'Diperbarui'), ('completed', 'Diselesaikan')], db_index=True, max_length=20)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draf'), ('completed', 'Selesai')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draf'), ('completed', 'Selesai')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_evaluation_history', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quality.evaluationrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('metrics', models.JSONField(default=dict)),
                ('narrative', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluationrecord',
            index=models.Index(fields=['evaluation_type', 'status', 'evaluation_date'], name='quality_eval_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitymetricsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='quality_snapshot_valid_period'),
        ),
    ]
