"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-development-key")

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",

    "apps.accounts",
    "apps.notifications",
    "apps.sources",
    "apps.articles",
    "apps.ingestion",
    "apps.crawlers",
    "apps.collection",
    "apps.entities",
    "apps.signals",
    "apps.locations",
    "apps.indicators",
    "apps.requirements",
    "apps.assessments",
    "apps.quality",
    "apps.dashboard.apps.DashboardConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard:overview"
LOGOUT_REDIRECT_URL = "login"

# Email untuk notifikasi (sinyal baru/eskalasi, early warning terbit).
# Default: EMAIL_BACKEND console, jadi email cuma tercetak di terminal
# runserver -- aman untuk dev, tidak butuh SMTP apapun. Untuk kirim
# email sungguhan, set environment variable berikut di .env lalu ganti
# EMAIL_BACKEND ke 'django.core.mail.backends.smtp.EmailBackend':
#   EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD,
#   EMAIL_USE_TLS
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "medintel@localhost",
)
# Dipakai untuk membuat link lengkap (bukan relatif) di isi email.
SITE_BASE_URL = os.getenv(
    "SITE_BASE_URL",
    "http://127.0.0.1:8000",
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DJANGO_LOG_LEVEL = os.getenv(
    "DJANGO_LOG_LEVEL",
    "INFO",
)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "[{levelname}] "
                "{asctime} "
                "{name} "
                "— {message}"
            ),
            "style": "{",
        },
        "simple": {
            "format": (
                "[{levelname}] "
                "{message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "apps.crawlers": {
            "handlers": [
                "console",
            ],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "apps.sources": {
            "handlers": [
                "console",
            ],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "apps.ingestion": {
            "handlers": [
                "console",
            ],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}

CRAWLER_CHEAP_FILTER_CHARS = 5000

CRAWLER_SAVE_ACCEPTED_DEBUG_HTML = False
CRAWLER_SAVE_REJECTED_DEBUG_HTML = False

# Jumlah kandidat link per halaman listing yang dievaluasi tiap crawl.
# Dinaikkan dari 30 -> 100 karena banyak artikel relevan terlewat begitu
# saja hanya karena berada di luar 30 link pertama pada halaman listing.
CRAWLER_CANDIDATE_LIMIT = 100

# Antrean koleksi berbasis database. Worker memperbarui heartbeat pada setiap
# checkpoint dan job dipulihkan bila lease ini kedaluwarsa.
COLLECTION_JOB_LEASE_SECONDS = int(
    os.getenv("COLLECTION_JOB_LEASE_SECONDS", "180")
)
COLLECTION_RETRY_BASE_SECONDS = int(
    os.getenv("COLLECTION_RETRY_BASE_SECONDS", "60")
)
COLLECTION_RETRY_MAX_SECONDS = int(
    os.getenv("COLLECTION_RETRY_MAX_SECONDS", "900")
)
