# Generated by Django 5.2.16 on 2026-07-28 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.SlugField(help_text='Kode internal sumber, misalnya kompas atau kemkes.', unique=True)),
                ('domain', models.CharField(help_text='Domain tanpa https://, www, atau path.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Masukkan domain tanpa protokol atau path, misalnya kompas.com.', regex='^[a-z0-9.-]+\\.[a-z]{2,}$')])),
                ('base_url', models.URLField()),
                ('source_type', models.CharField(choices=[('government', 'Instansi Pemerintah'), ('national_media', 'Media Nasional'), ('local_media', 'Media Lokal'), ('international_media', 'Media Internasional'), ('other', 'Lainnya')], max_length=30)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_verified', 'is_active'], name='source_verified_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='SourceUrlPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Pola URL atau path, misalnya /read/, /search/, atau ekspresi reguler.', max_length=500)),
                ('pattern_type', models.CharField(choices=[('allow', 'Diizinkan'), ('deny', 'Ditolak')], max_length=10)),
                ('is_regex', models.BooleanField(default=False, help_text='Aktifkan apabila pattern menggunakan regular expression.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_patterns', to='sources.source')),
            ],
            options={
                'ordering': ['source', 'pattern_type', 'pattern'],
                'constraints': [models.UniqueConstraint(fields=('source', 'pattern', 'pattern_type'), name='unique_source_url_pattern')],
            },
        ),
    ]
