# Generated by Django 5.2.16 on 2026-07-29 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSeedUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('seed_type', models.CharField(choices=[('listing', 'Halaman Daftar Artikel'), ('rss', 'RSS/Atom Feed'), ('sitemap', 'XML Sitemap'), ('direct', 'URL Artikel Langsung')], db_index=True, default='listing', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Angka lebih kecil diproses lebih dahulu.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'url'],
            },
        ),
        migrations.AlterModelOptions(
            name='sourceurlpattern',
            options={'ordering': ['priority', 'pattern_type', 'pattern']},
        ),
        migrations.RemoveConstraint(
            model_name='sourceurlpattern',
            name='unique_source_url_pattern',
        ),
        migrations.RemoveField(
            model_name='sourceurlpattern',
            name='is_regex',
        ),
        migrations.AddField(
            model_name='source',
            name='allow_subdomains',
            field=models.BooleanField(default=False, help_text='Izinkan crawler mengambil URL dari subdomain sumber.'),
        ),
        migrations.AddField(
            model_name='source',
            name='crawl_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Aktifkan agar sumber dapat diproses oleh crawler otomatis.'),
        ),
        migrations.AddField(
            model_name='source',
            name='crawl_strategy',
            field=models.CharField(choices=[('html', 'HTML Listing'), ('rss', 'RSS/Atom'), ('sitemap', 'XML Sitemap'), ('manual', 'Manual Only')], db_index=True, default='html', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='crawler_notes',
            field=models.TextField(blank=True, help_text='Catatan teknis mengenai struktur halaman atau pembatasan crawler.'),
        ),
        migrations.AddField(
            model_name='source',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='max_articles_per_run',
            field=models.PositiveIntegerField(default=50, help_text='Jumlah maksimum artikel yang diproses dalam satu eksekusi crawler.'),
        ),
        migrations.AddField(
            model_name='source',
            name='request_delay_seconds',
            field=models.FloatField(default=1.0, help_text='Jeda minimum antarpermintaan HTTP dalam detik.'),
        ),
        migrations.AddField(
            model_name='source',
            name='request_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=20, help_text='Batas waktu setiap permintaan HTTP dalam detik.'),
        ),
        migrations.AddField(
            model_name='source',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User-Agent khusus sumber. Kosongkan untuk memakai User-Agent default.', max_length=300),
        ),
        migrations.AddField(
            model_name='sourceurlpattern',
            name='match_type',
            field=models.CharField(choices=[('prefix', 'Awalan URL'), ('contains', 'Mengandung'), ('regex', 'Regular Expression')], db_index=True, default='prefix', max_length=20),
        ),
        migrations.AddField(
            model_name='sourceurlpattern',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Angka lebih kecil dievaluasi lebih dahulu.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='base_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('government', 'Instansi Pemerintah'), ('national_media', 'Media Nasional'), ('local_media', 'Media Lokal'), ('international_media', 'Media Internasional'), ('health_organization', 'Organisasi Kesehatan'), ('research_institution', 'Lembaga Penelitian'), ('other', 'Lainnya')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sourceurlpattern',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RemoveField(
            model_name="sourceurlpattern",
            name="id",
        ),
        migrations.AddField(
            model_name="sourceurlpattern",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='sourceurlpattern',
            name='pattern',
            field=models.CharField(help_text='Bisa berupa path, URL penuh, potongan teks, atau regular expression.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sourceurlpattern',
            name='pattern_type',
            field=models.CharField(choices=[('allow', 'Izinkan'), ('deny', 'Tolak')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['crawl_enabled', 'crawl_strategy'], name='source_crawl_strategy_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceurlpattern',
            index=models.Index(fields=['source', 'pattern_type', 'is_active'], name='source_pattern_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceurlpattern',
            constraint=models.UniqueConstraint(fields=('source', 'pattern_type', 'match_type', 'pattern'), name='unique_source_url_pattern'),
        ),
        migrations.AddField(
            model_name='sourceseedurl',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_urls', to='sources.source'),
        ),
        migrations.AddIndex(
            model_name='sourceseedurl',
            index=models.Index(fields=['source', 'seed_type', 'is_active'], name='source_seed_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceseedurl',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='unique_source_seed_url'),
        ),
    ]
