# Generated by Django 5.2.13 on 2026-04-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword'), ('disease', 'Disease'), ('location', 'Location'), ('custom', 'Custom')], default='keyword', max_length=30)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField(blank=True, default='')),
                ('rss_url', models.URLField(blank=True, default='')),
                ('country_code', models.CharField(db_index=True, default='ID', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('validate', 'Validate'), ('approve', 'Approve'), ('mark_noise', 'Mark Noise'), ('manual_edit', 'Manual Edit')], db_index=True, max_length=30)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('level', models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('regency', 'Regency'), ('city', 'City'), ('district', 'District'), ('village', 'Village'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('country_code', models.CharField(db_index=True, default='ID', max_length=10)),
                ('province_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('city_regency_code', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='intel.location')),
            ],
            options={
                'ordering': ['level', 'display_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('normalized_alias', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='intel.location')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('disease_tag', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('threat_score', models.IntegerField(db_index=True, default=0)),
                ('raw_location_text', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('geocode_status', models.CharField(choices=[('OK', 'OK'), ('EMPTY_LOC', 'EMPTY_LOC'), ('NOT_FOUND', 'NOT_FOUND'), ('NET_ERR', 'NET_ERR'), ('SKIP_NOISE', 'SKIP_NOISE'), ('SKIP_TOO_GENERAL', 'SKIP_TOO_GENERAL'), ('SKIP_LOW_CONF', 'SKIP_LOW_CONF'), ('MANUAL', 'MANUAL'), ('PENDING', 'PENDING')], db_index=True, default='PENDING', max_length=30)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('validated', 'Validated'), ('noise', 'Noise'), ('approved', 'Approved')], db_index=True, default='raw', max_length=20)),
                ('validation_notes', models.TextField(blank=True, default='')),
                ('is_high_risk', models.BooleanField(db_index=True, default=False)),
                ('approved_for_mapping', models.BooleanField(db_index=True, default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_signals', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='intel.source')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_location_text', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('gazetteer', 'Gazetteer'), ('alias', 'Alias')], default='auto', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_links', to='intel.location')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_locations', to='intel.signal')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['normalized_name'], name='intel_locat_normali_b68345_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['level'], name='intel_locat_level_44eec5_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['province_code'], name='intel_locat_provinc_ac1554_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city_regency_code'], name='intel_locat_city_re_ac8fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='intel_locat_is_acti_8981fe_idx'),
        ),
        migrations.AddIndex(
            model_name='locationalias',
            index=models.Index(fields=['normalized_alias'], name='intel_locat_normali_baf8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='locationalias',
            index=models.Index(fields=['is_active'], name='intel_locat_is_acti_6a488c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationalias',
            unique_together={('location', 'alias')},
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['status'], name='intel_signa_status_cc8331_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['disease_tag'], name='intel_signa_disease_0eb4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['geocode_status'], name='intel_signa_geocode_29c3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['threat_score'], name='intel_signa_threat__c61ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['approved_for_mapping'], name='intel_signa_approve_3b8ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['is_high_risk'], name='intel_signa_is_high_559a3d_idx'),
        ),
    ]
