# Generated by Django 5.2.13 on 2026-04-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('cluster_city_48h', 'Cluster in City 48h'), ('high_avg_score', 'High Average Score'), ('new_location', 'New Location')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('signal_count', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('first_signal_at', models.DateTimeField(blank=True, null=True)),
                ('last_signal_at', models.DateTimeField(blank=True, null=True)),
                ('rule_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('dedup_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='intel.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
