# Generated by Django 5.2.13 on 2026-04-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='admin_kabkota',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='signal',
            name='admin_province',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='signal',
            name='location_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signallocation',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='intel.signal'),
        ),
    ]
