# Generated by Django 5.2.13 on 2026-04-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0005_signal_scoring_breakdown_signal_scoring_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='risk_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
