# Generated by Django 5.2.13 on 2026-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0008_signal_assessment_5w1h_signal_assessment_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedSourceURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000, unique=True)),
                ('resolved_url', models.URLField(max_length=1000)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('method', models.CharField(blank=True, default='', max_length=60)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='resolved_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='signal',
            name='url_resolution_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='signal',
            name='url_resolution_method',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='signal',
            name='url_resolution_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='signal',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
