# Generated by Django 5.2.13 on 2026-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0010_add_signal_url_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherDomainAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('normalized_alias', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
    ]
