# Generated by Django 5.2.13 on 2026-05-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0011_publisherdomainalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('disease_tag', models.CharField(blank=True, db_index=True, max_length=128)),
                ('location_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('location_level', models.CharField(blank=True, max_length=32)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('validated_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('noise_count', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('avg_confidence', models.FloatField(default=0)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('ready_for_approval', 'Ready for Approval'), ('approved', 'Approved'), ('noise', 'Noise'), ('archived', 'Archived')], db_index=True, default='open', max_length=32)),
                ('summary', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-max_score', '-signal_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='approval_recommendation',
            field=models.CharField(choices=[('approve', 'Recommended to Approve'), ('review', 'Needs Manual Review'), ('fix_location', 'Needs Location Fix'), ('noise', 'Recommended as Noise'), ('duplicate', 'Duplicate Candidate')], db_index=True, default='review', max_length=32),
        ),
        migrations.AddField(
            model_name='signal',
            name='confidence_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='triage_priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('noise_candidate', 'Noise Candidate')], db_index=True, default='medium', max_length=32),
        ),
        migrations.AddField(
            model_name='signal',
            name='triage_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='signal',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.CharField(choices=[('province', 'Province'), ('regency', 'Regency'), ('city', 'City')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='signal',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='intel.signalcluster'),
        ),
    ]
