# Generated by Django 5.2.16 on 2026-07-28 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=1000)),
                ('normalized_url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content_text', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('processing_status', models.CharField(choices=[('new', 'Baru'), ('validated', 'Tervalidasi'), ('processing', 'Sedang Diproses'), ('processed', 'Selesai Diproses'), ('rejected', 'Ditolak'), ('failed', 'Gagal')], db_index=True, default='new', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sources.source')),
            ],
            options={
                'ordering': ['-published_at', '-crawled_at'],
                'indexes': [models.Index(fields=['source', 'published_at'], name='article_source_pub_idx'), models.Index(fields=['processing_status', 'crawled_at'], name='article_status_crawl_idx'), models.Index(fields=['content_hash', 'source'], name='article_hash_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'content_hash'), name='unique_article_source_content')],
            },
        ),
    ]
