# Generated by Django 5.2.16 on 2026-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='articles', through='entities.ArticleDisease', to='entities.disease'),
        ),
        migrations.AddField(
            model_name='article',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='articles', through='entities.ArticleLocation', to='entities.location'),
        ),
    ]
