# Generated by Django 5.2.11 on 2026-03-03 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_tag', models.CharField(db_index=True, max_length=100)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('final_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('threat_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('raw', 'Raw'), ('triaged', 'Triaged'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='raw', max_length=20)),
                ('dedup_hash', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(default='id', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('rss_url', models.URLField(blank=True, null=True)),
                ('country_code', models.CharField(default='ID', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('kabupaten', 'Kabupaten'), ('kota', 'Kota'), ('kecamatan', 'Kecamatan'), ('desa', 'Desa'), ('facility', 'Facility'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('country_code', models.CharField(default='ID', max_length=8)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('geocode_quality', models.CharField(default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='intel.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=200)),
                ('alias_norm', models.CharField(db_index=True, max_length=220)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='intel.location')),
            ],
        ),
        migrations.CreateModel(
            name='SignalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_location_text', models.CharField(blank=True, max_length=250, null=True)),
                ('method', models.CharField(choices=[('gazetteer', 'Gazetteer'), ('regex', 'Regex'), ('ner', 'NER'), ('manual', 'Manual')], default='gazetteer', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('geocode_status', models.CharField(choices=[('ok', 'OK'), ('not_found', 'Not Found'), ('empty', 'Empty'), ('skip_noise', 'Skip Noise'), ('skip_general', 'Skip General'), ('net_err', 'Network Error'), ('timeout', 'Timeout'), ('rate_limit', 'Rate Limit'), ('service_err', 'Service Error')], default='empty', max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_locations', to='intel.location')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_locations', to='intel.signal')),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='intel.source'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='intel_locat_name_3f3b03_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['level'], name='intel_locat_level_44eec5_idx'),
        ),
        migrations.AddIndex(
            model_name='signallocation',
            index=models.Index(fields=['geocode_status'], name='intel_signa_geocode_594322_idx'),
        ),
        migrations.AddIndex(
            model_name='signallocation',
            index=models.Index(fields=['method'], name='intel_signa_method_4d1e35_idx'),
        ),
        migrations.AddIndex(
            model_name='signallocation',
            index=models.Index(fields=['is_primary'], name='intel_signa_is_prim_77a83d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['disease_tag'], name='intel_signa_disease_0eb4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['threat_score'], name='intel_signa_threat__c61ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['status'], name='intel_signa_status_cc8331_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['published_at'], name='intel_signa_publish_f787d1_idx'),
        ),
    ]
