# Generated by Django 5.2.12 on 2026-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='detected_diseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='event_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='severity_nlp',
            field=models.IntegerField(default=0),
        ),
    ]
