# Generated by Django 5.2.12 on 2026-03-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_signal_detected_diseases_signal_event_types_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AlterModelOptions(
            name='locationalias',
            options={'ordering': ['alias_text']},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-published_at', '-crawled_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='signallocation',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country_code'], name='intel_locat_country_e39701_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['parent'], name='intel_locat_parent__95fcad_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='intel_locat_is_acti_8981fe_idx'),
        ),
        migrations.AddIndex(
            model_name='locationalias',
            index=models.Index(fields=['alias_norm'], name='intel_locat_alias_n_889141_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['crawled_at'], name='intel_signa_crawled_d43b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['created_at'], name='intel_signa_created_a66fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['severity_nlp'], name='intel_signa_severit_b328ae_idx'),
        ),
        migrations.AddIndex(
            model_name='signallocation',
            index=models.Index(fields=['location'], name='intel_signa_locatio_1bea74_idx'),
        ),
        migrations.AddIndex(
            model_name='signallocation',
            index=models.Index(fields=['signal'], name='intel_signa_signal__c2f414_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['name'], name='intel_sourc_name_cd554c_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active'], name='intel_sourc_is_acti_6952f8_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['country_code'], name='intel_sourc_country_9f98d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'level', 'parent', 'country_code'), name='uq_location_name_level_parent_country'),
        ),
        migrations.AddConstraint(
            model_name='locationalias',
            constraint=models.UniqueConstraint(fields=('location', 'alias_norm'), name='uq_location_alias_norm_per_location'),
        ),
        migrations.AddConstraint(
            model_name='signallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('signal',), name='uq_one_primary_location_per_signal'),
        ),
    ]
