# Generated by Django 5.2.13 on 2026-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_signal_admin_kabkota_signal_admin_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='scoring_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='signal',
            name='scoring_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
