# Generated by Django 5.2.13 on 2026-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0006_signal_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='geocode_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('matched', 'Matched'), ('gazetteer_only', 'Gazetteer Only'), ('manual', 'Manual'), ('empty_loc', 'Empty Location'), ('not_found', 'Not Found'), ('net_err', 'Network Error'), ('skip_noise', 'Skip Noise'), ('skip_too_general', 'Skip Too General'), ('skip_low_conf', 'Skip Low Confidence'), ('OK', 'OK'), ('EMPTY_LOC', 'EMPTY_LOC'), ('NOT_FOUND', 'NOT_FOUND'), ('NET_ERR', 'NET_ERR'), ('SKIP_NOISE', 'SKIP_NOISE'), ('SKIP_TOO_GENERAL', 'SKIP_TOO_GENERAL'), ('SKIP_LOW_CONF', 'SKIP_LOW_CONF'), ('MANUAL', 'MANUAL'), ('PENDING', 'PENDING')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='signallocation',
            name='method',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('gazetteer', 'Gazetteer'), ('alias', 'Alias'), ('location_exact', 'Location Exact'), ('location_alias', 'Location Alias'), ('legacy_admin_normalized', 'Legacy Admin Normalized'), ('legacy_admin_province_normalized', 'Legacy Admin Province Normalized')], default='auto', max_length=50),
        ),
    ]
