# Generated by Django 5.2.13 on 2026-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0007_alter_signal_geocode_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='assessment_5w1h',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='signal',
            name='assessment_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='signal',
            name='assessment_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='assessment_source_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='signal',
            name='assessment_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='signal',
            name='assessment_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
