# Generated by Django 5.2.16 on 2026-07-28 10:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_articledisease_validation_notes_and_more'),
        ('indicators', '0002_indicatorreviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Contoh: IR-001 atau peningkatan-klb.', unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('disease_event', 'Kejadian Penyakit'), ('geographic_spread', 'Penyebaran Geografis'), ('cross_border', 'Ancaman Lintas Negara'), ('impact', 'Dampak Kesehatan'), ('anomaly', 'Kejadian Tidak Lazim'), ('response', 'Respons Pemerintah'), ('other', 'Lainnya')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], db_index=True, default='medium', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intelligence_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RequirementDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_links', to='entities.disease')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_diseases', to='requirements.intelligencerequirement')),
            ],
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='intelligence_requirements', through='requirements.RequirementDisease', to='entities.disease'),
        ),
        migrations.CreateModel(
            name='RequirementIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('relevance_reason', models.TextField(blank=True)),
                ('matched_by', models.CharField(choices=[('system', 'Sistem'), ('analyst', 'Analis')], default='system', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_matches', to='indicators.indicator')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_matches', to='requirements.intelligencerequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requirement_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='intelligence_requirements', through='requirements.RequirementIndicator', to='indicators.indicator'),
        ),
        migrations.CreateModel(
            name='RequirementKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('keyword_type', models.CharField(choices=[('disease', 'Penyakit'), ('trend', 'Tren'), ('impact', 'Dampak'), ('location', 'Lokasi'), ('response', 'Respons'), ('anomaly', 'Anomali'), ('general', 'Umum')], db_index=True, default='general', max_length=20)),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='requirements.intelligencerequirement')),
            ],
            options={
                'ordering': ['keyword_type', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='RequirementLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('include_descendants', models.BooleanField(default=True, help_text='Apabila aktif, wilayah di bawah lokasi ini juga dianggap relevan.')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_links', to='entities.location')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_locations', to='requirements.intelligencerequirement')),
            ],
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='intelligence_requirements', through='requirements.RequirementLocation', to='entities.location'),
        ),
        migrations.AddConstraint(
            model_name='requirementdisease',
            constraint=models.UniqueConstraint(fields=('requirement', 'disease'), name='unique_requirement_disease'),
        ),
        migrations.AddIndex(
            model_name='requirementindicator',
            index=models.Index(fields=['requirement', 'relevance_score'], name='reqindicator_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementindicator',
            constraint=models.UniqueConstraint(fields=('requirement', 'indicator'), name='unique_requirement_indicator'),
        ),
        migrations.AddConstraint(
            model_name='requirementkeyword',
            constraint=models.UniqueConstraint(fields=('requirement', 'keyword'), name='unique_requirement_keyword'),
        ),
        migrations.AddConstraint(
            model_name='requirementlocation',
            constraint=models.UniqueConstraint(fields=('requirement', 'location'), name='unique_requirement_location'),
        ),
        migrations.AddIndex(
            model_name='intelligencerequirement',
            index=models.Index(fields=['is_active', 'priority'], name='intelreq_active_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencerequirement',
            index=models.Index(fields=['requirement_type', 'is_active'], name='intelreq_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='intelligencerequirement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='requirement_valid_date_range'),
        ),
    ]
