# Generated by Django 5.2.16 on 2026-08-09 14:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_workspace_fields(apps, schema_editor):
    IntelligenceRequirement = apps.get_model(
        "requirements", "IntelligenceRequirement"
    )
    for requirement in IntelligenceRequirement.objects.all().iterator():
        requirement.question = (
            requirement.description.strip()
            or requirement.title.strip()
        )
        requirement.status = "active" if requirement.is_active else "closed"
        if not requirement.is_active and not requirement.closure_notes:
            requirement.closure_notes = "Dimigrasikan dari kebutuhan nonaktif."
        requirement.save(
            update_fields=["question", "status", "closure_notes"]
        )


def reverse_workspace_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_locations_app'),
        ('collection', '0004_collectionsession_collectionjob_session'),
        ('entities', '0009_remove_location_state'),
        ('indicators', '0003_alter_indicator_location_app'),
        ('locations', '0001_move_location_from_entities'),
        ('requirements', '0002_alter_location_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Dibuat'), ('updated', 'Diperbarui'), ('activated', 'Diaktifkan'), ('answered', 'Dinyatakan Terjawab'), ('closed', 'Ditutup'), ('collection_linked', 'Sesi Koleksi Ditautkan'), ('article_linked', 'Artikel Ditautkan'), ('article_unlinked', 'Tautan Artikel Dilepas'), ('gap_opened', 'Kesenjangan Dibuka'), ('gap_resolved', 'Kesenjangan Dipenuhi')], db_index=True, max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draf'), ('active', 'Aktif'), ('answered', 'Terjawab'), ('closed', 'Ditutup')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draf'), ('active', 'Aktif'), ('answered', 'Terjawab'), ('closed', 'Ditutup')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementInformationGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Terbuka'), ('resolved', 'Terpenuhi'), ('cancelled', 'Dibatalkan')], db_index=True, default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', '-priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_intelligence_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='answer_summary',
            field=models.TextField(blank=True, help_text='Simpulan analitis yang menjawab pertanyaan utama.'),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_intelligence_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intelligence_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_intelligence_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='closure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='question',
            field=models.TextField(default='', help_text='Pertanyaan utama yang harus dijawab oleh proses intelijen.'),
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draf'), ('active', 'Aktif'), ('answered', 'Terjawab'), ('closed', 'Ditutup')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='RequirementArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('relevance_reason', models.TextField(blank=True)),
                ('link_source', models.CharField(choices=[('collection', 'Sesi Koleksi'), ('analyst', 'Analis')], default='analyst', max_length=20)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_links', to='articles.article')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requirement_articles', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='requirements.intelligencerequirement')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='intelligence_requirements', through='requirements.RequirementArticle', to='articles.article'),
        ),
        migrations.CreateModel(
            name='RequirementCollectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requirement_collection_sessions', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='requirements.intelligencerequirement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='collection.collectionsession')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.AddField(
            model_name='intelligencerequirement',
            name='collection_sessions',
            field=models.ManyToManyField(blank=True, related_name='intelligence_requirements', through='requirements.RequirementCollectionSession', to='collection.collectionsession'),
        ),
        migrations.AddIndex(
            model_name='intelligencerequirement',
            index=models.Index(fields=['status', 'priority', 'updated_at'], name='intelreq_status_priority_idx'),
        ),
        migrations.AddField(
            model_name='requirementhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_requirement_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementhistory',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='requirements.intelligencerequirement'),
        ),
        migrations.AddField(
            model_name='requirementinformationgap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirement_information_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementinformationgap',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_gaps', to='requirements.intelligencerequirement'),
        ),
        migrations.AddField(
            model_name='requirementinformationgap',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_requirement_information_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='requirementarticle',
            constraint=models.UniqueConstraint(fields=('requirement', 'article'), name='unique_requirement_article'),
        ),
        migrations.AddConstraint(
            model_name='requirementcollectionsession',
            constraint=models.UniqueConstraint(fields=('requirement', 'session'), name='unique_requirement_collection_session'),
        ),
        migrations.RunPython(
            populate_workspace_fields,
            reverse_workspace_fields,
        ),
    ]
