# Generated by Django 5.2.16 on 2026-07-28 15:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_diseases_article_locations'),
        ('signals', '0002_signal_analyst_judgement_signal_implication_and_more'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('completed', 'Selesai'), ('superseded', 'Digantikan')], db_index=True, default='draft', max_length=20)),
                ('urgency_score', models.PositiveSmallIntegerField(help_text='Seberapa cepat sinyal memerlukan perhatian.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact_score', models.PositiveSmallIntegerField(help_text='Besarnya potensi dampak kesehatan atau operasional.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('geographic_scope_score', models.PositiveSmallIntegerField(help_text='Luas cakupan geografis kejadian.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('development_speed_score', models.PositiveSmallIntegerField(help_text='Kecepatan perkembangan atau perubahan kejadian.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('vulnerability_score', models.PositiveSmallIntegerField(help_text='Kerentanan kelompok atau wilayah terdampak.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source_reliability_score', models.FloatField(help_text='Agregasi reliabilitas sumber pendukung.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('information_credibility_score', models.FloatField(help_text='Agregasi kredibilitas informasi pendukung.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('information_completeness_score', models.FloatField(help_text='Kelengkapan informasi yang tersedia.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('evidence_consistency_score', models.FloatField(help_text='Konsistensi antar-bukti dan antar-sumber.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('priority_score', models.FloatField(db_index=True, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence_score', models.FloatField(db_index=True, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recommended_priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], db_index=True, max_length=20)),
                ('recommended_confidence', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], db_index=True, max_length=20)),
                ('analytical_judgement', models.TextField()),
                ('implications', models.TextField(blank=True)),
                ('recommended_actions', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_assessments', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='signals.signal')),
            ],
            options={
                'ordering': ['-is_current', '-version'],
            },
        ),
        migrations.CreateModel(
            name='InformationGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gap_type', models.CharField(choices=[('case_data', 'Data Kasus'), ('death_data', 'Data Kematian'), ('location', 'Lokasi'), ('time', 'Waktu Kejadian'), ('disease_confirmation', 'Konfirmasi Penyakit'), ('official_confirmation', 'Konfirmasi Resmi'), ('source_corroboration', 'Penguatan Sumber'), ('response', 'Respons'), ('other', 'Lainnya')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Terbuka'), ('resolved', 'Terpenuhi'), ('cancelled', 'Dibatalkan')], db_index=True, default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_information_gaps', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_gaps', to='assessments.signalassessment')),
            ],
            options={
                'ordering': ['status', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('historical_accuracy_score', models.FloatField(help_text='Konsistensi ketepatan informasi sumber sebelumnya.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('authority_score', models.FloatField(help_text='Kewenangan atau kompetensi sumber pada topik terkait.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('transparency_score', models.FloatField(help_text='Kejelasan asal data, narasumber, dan metode pelaporan.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('independence_score', models.FloatField(help_text='Derajat independensi sumber dari sumber lain.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reliability_score', models.FloatField(db_index=True, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reliability_level', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('very_high', 'Sangat Tinggi'), ('unassessed', 'Belum Dinilai')], db_index=True, default='unassessed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_evaluations', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_evaluations', to='signals.signal')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_evaluations', to='sources.source')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corroboration_score', models.FloatField(help_text='Tingkat dukungan dari sumber atau artikel lain.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('consistency_score', models.FloatField(help_text='Konsistensi isi dengan bukti lain yang tersedia.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('specificity_score', models.FloatField(help_text='Kejelasan unsur penyakit, lokasi, waktu, dan angka.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timeliness_score', models.FloatField(help_text='Kebaruan informasi terhadap kejadian yang dinilai.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('credibility_score', models.FloatField(db_index=True, editable=False, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('credibility_level', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('very_high', 'Sangat Tinggi'), ('unassessed', 'Belum Dinilai')], db_index=True, default='unassessed', max_length=20)),
                ('supports_signal', models.BooleanField(default=True)),
                ('contradiction_notes', models.TextField(blank=True, help_text='Diisi apabila informasi bertentangan dengan bukti lain.')),
                ('notes', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='information_evaluations', to='articles.article')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_evaluations', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_evaluations', to='signals.signal')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['signal', 'credibility_level'], name='info_eval_signal_level_idx')],
                'constraints': [models.UniqueConstraint(fields=('signal', 'article'), name='unique_signal_article_evaluation')],
            },
        ),
        migrations.AddIndex(
            model_name='signalassessment',
            index=models.Index(fields=['signal', 'is_current', 'status'], name='assessment_signal_current_idx'),
        ),
        migrations.AddIndex(
            model_name='signalassessment',
            index=models.Index(fields=['recommended_priority', 'recommended_confidence'], name='assessment_rec_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalassessment',
            constraint=models.UniqueConstraint(fields=('signal', 'version'), name='unique_signal_assessment_version'),
        ),
        migrations.AddConstraint(
            model_name='signalassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('signal',), name='unique_current_signal_assessment'),
        ),
        migrations.AddIndex(
            model_name='sourceevaluation',
            index=models.Index(fields=['signal', 'reliability_level'], name='src_eval_signal_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceevaluation',
            constraint=models.UniqueConstraint(fields=('signal', 'source'), name='unique_signal_source_evaluation'),
        ),
    ]
