# Generated by Django 5.2.16 on 2026-08-01 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_diseases_article_locations'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleValidationAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validation_status', models.CharField(choices=[('pending', 'Perlu Tinjau'), ('validated', 'Tervalidasi'), ('rejected', 'Tidak Relevan')], db_index=True, default='pending', max_length=20)),
                ('source_reliability', models.CharField(choices=[('A', 'Sepenuhnya dapat dipercaya'), ('B', 'Biasanya dapat dipercaya'), ('C', 'Cukup dapat dipercaya'), ('D', 'Biasanya tidak dapat dipercaya'), ('E', 'Tidak dapat dipercaya'), ('F', 'Belum dapat dinilai')], db_index=True, default='F', max_length=1)),
                ('information_credibility', models.PositiveSmallIntegerField(choices=[(1, 'Dikonfirmasi oleh sumber lain'), (2, 'Kemungkinan besar benar'), (3, 'Mungkin benar'), (4, 'Diragukan'), (5, 'Kemungkinan tidak benar'), (6, 'Belum dapat dinilai')], db_index=True, default=6)),
                ('relevance_notes', models.TextField(blank=True)),
                ('assessment_notes', models.TextField(blank=True)),
                ('supporting_factors', models.JSONField(blank=True, default=list)),
                ('limiting_factors', models.JSONField(blank=True, default=list)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_assessment', to='articles.article')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_validation_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['validation_status', 'updated_at'], name='article_validation_status_idx'), models.Index(fields=['source_reliability', 'information_credibility'], name='article_admiralty_code_idx')],
            },
        ),
    ]
