# Generated by Django 5.2.16 on 2026-08-01 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_articlevalidationassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleValidationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Perlu Tinjau'), ('validated', 'Tervalidasi'), ('rejected', 'Tidak Relevan')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Perlu Tinjau'), ('validated', 'Tervalidasi'), ('rejected', 'Tidak Relevan')], max_length=20)),
                ('previous_source_reliability', models.CharField(blank=True, choices=[('A', 'Sepenuhnya dapat dipercaya'), ('B', 'Biasanya dapat dipercaya'), ('C', 'Cukup dapat dipercaya'), ('D', 'Biasanya tidak dapat dipercaya'), ('E', 'Tidak dapat dipercaya'), ('F', 'Belum dapat dinilai')], max_length=1)),
                ('new_source_reliability', models.CharField(choices=[('A', 'Sepenuhnya dapat dipercaya'), ('B', 'Biasanya dapat dipercaya'), ('C', 'Cukup dapat dipercaya'), ('D', 'Biasanya tidak dapat dipercaya'), ('E', 'Tidak dapat dipercaya'), ('F', 'Belum dapat dinilai')], max_length=1)),
                ('previous_information_credibility', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Dikonfirmasi oleh sumber lain'), (2, 'Kemungkinan besar benar'), (3, 'Mungkin benar'), (4, 'Diragukan'), (5, 'Kemungkinan tidak benar'), (6, 'Belum dapat dinilai')], null=True)),
                ('new_information_credibility', models.PositiveSmallIntegerField(choices=[(1, 'Dikonfirmasi oleh sumber lain'), (2, 'Kemungkinan besar benar'), (3, 'Mungkin benar'), (4, 'Diragukan'), (5, 'Kemungkinan tidak benar'), (6, 'Belum dapat dinilai')])),
                ('change_notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assessments.articlevalidationassessment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_validation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
