# Generated by Django 5.2.16 on 2026-08-05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_articlevalidationhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyWarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("monitoring", "Pemantauan"),
                            ("advisory", "Waspada"),
                            ("high", "Peringatan Tinggi"),
                            ("critical", "Peringatan Kritis"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("medium", "Sedang"),
                            ("high", "Tinggi"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Diterbitkan"),
                            ("superseded", "Digantikan"),
                            ("closed", "Ditutup"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("analytical_judgement", models.TextField()),
                ("implications", models.TextField(blank=True)),
                ("recommended_actions", models.TextField()),
                ("information_gaps", models.TextField(blank=True)),
                ("decision_notes", models.TextField()),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="early_warning",
                        to="assessments.signalassessment",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_early_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_early_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="early_warnings",
                        to="signals.signal",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_current", "-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "level", "issued_at"],
                        name="warning_status_level_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("signal", "version"),
                        name="unique_signal_warning_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("signal",),
                        name="unique_current_early_warning",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EarlyWarningHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("issued", "Diterbitkan"),
                            ("superseded", "Digantikan"),
                            ("closed", "Ditutup"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("issued", "Diterbitkan"),
                            ("superseded", "Digantikan"),
                            ("closed", "Ditutup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("issued", "Diterbitkan"),
                            ("superseded", "Digantikan"),
                            ("closed", "Ditutup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="early_warning_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="assessments.earlywarning",
                    ),
                ),
            ],
            options={"ordering": ["-changed_at"]},
        ),
    ]
