# Generated by Django 5.2.6 on 2026-08-05 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_earlywarning_earlywarninghistory'),
        ('signals', '0002_signal_analyst_judgement_signal_implication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('approved', 'Ditetapkan'), ('in_progress', 'Ditindaklanjuti'), ('completed', 'Selesai'), ('canceled', 'Dibatalkan'), ('superseded', 'Digantikan')], db_index=True, default='draft', max_length=20)),
                ('urgency', models.CharField(choices=[('routine', 'Rutin'), ('priority', 'Prioritas'), ('urgent', 'Mendesak'), ('immediate', 'Segera')], db_index=True, max_length=20)),
                ('action_category', models.CharField(choices=[('collection', 'Pengumpulan Informasi'), ('verification', 'Verifikasi'), ('monitoring', 'Pemantauan'), ('coordination', 'Koordinasi'), ('preparedness', 'Kesiapsiagaan'), ('operational_support', 'Dukungan Operasional')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('situation_summary', models.TextField()),
                ('objective', models.TextField()),
                ('recommended_action', models.TextField()),
                ('target_unit', models.CharField(max_length=500)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('decision_rationale', models.TextField(blank=True)),
                ('success_indicators', models.TextField()),
                ('assumptions', models.TextField(blank=True)),
                ('information_gaps', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_intelligence_recommendations', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_recommendation', to='assessments.signalassessment')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_intelligence_recommendations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intelligence_recommendations', to=settings.AUTH_USER_MODEL)),
                ('early_warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_recommendations', to='assessments.earlywarning')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_recommendations', to='signals.signal')),
            ],
            options={
                'ordering': ['-is_current', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceRecommendationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('drafted', 'Draf Dibentuk'), ('approved', 'Ditetapkan'), ('started', 'Tindak Lanjut Dimulai'), ('completed', 'Diselesaikan'), ('canceled', 'Dibatalkan'), ('superseded', 'Digantikan')], db_index=True, max_length=20)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draf'), ('approved', 'Ditetapkan'), ('in_progress', 'Ditindaklanjuti'), ('completed', 'Selesai'), ('canceled', 'Dibatalkan'), ('superseded', 'Digantikan')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draf'), ('approved', 'Ditetapkan'), ('in_progress', 'Ditindaklanjuti'), ('completed', 'Selesai'), ('canceled', 'Dibatalkan'), ('superseded', 'Digantikan')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_recommendation_history', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assessments.intelligencerecommendation')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intelligencerecommendation',
            index=models.Index(fields=['status', 'urgency', 'due_date'], name='intel_rec_status_urgency_idx'),
        ),
        migrations.AddConstraint(
            model_name='intelligencerecommendation',
            constraint=models.UniqueConstraint(fields=('signal', 'version'), name='unique_signal_recommendation_version'),
        ),
        migrations.AddConstraint(
            model_name='intelligencerecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('signal',), name='unique_current_intel_recommendation'),
        ),
    ]
