from django.urls import path

from . import views
from apps.assessments import views as assessment_views
from apps.assessments import early_warning_views
from apps.assessments import threat_map_views
from apps.assessments import disease_priority_views
from apps.assessments import intelligence_recommendation_views
from apps.assessments import executive_dashboard_views
from apps.assessments import report_views
from apps.signals import views as signal_views
from apps.requirements import views as requirement_views


app_name = "dashboard"

urlpatterns = [
    path(
        "kebutuhan-intelijen/",
        requirement_views.intelligence_requirement_workspace,
        name="intelligence-requirement",
    ),
    path(
        "",
        views.dashboard_overview,
        name="overview",
    ),
    path(
        "validasi-artikel/",
        views.article_validation,
        name="article-validation",
    ),
    path(
        "artikel/<uuid:article_id>/hapus/",
        views.article_delete,
        name="article-delete",
    ),
    path(
        "daftar-artikel/",
        views.article_list,
        name="article-list",
    ),
    path(
        "sinyal-intelijen/",
        signal_views.signal_workspace,
        name="signal-workspace",
    ),
    path(
        "assessment-ancaman/",
        assessment_views.threat_assessment_workspace,
        name="threat-assessment",
    ),
    path(
        "peringatan-dini/",
        early_warning_views.early_warning_workspace,
        name="early-warning",
    ),
    path(
        "peta-ancaman/",
        threat_map_views.threat_map_workspace,
        name="threat-map",
    ),
    path(
        "penyakit-prioritas/",
        disease_priority_views.disease_priority_workspace,
        name="disease-priority",
    ),
    path(
        "rekomendasi-intelijen/",
        intelligence_recommendation_views.intelligence_recommendation_workspace,
        name="intelligence-recommendation",
    ),
    path(
        "dashboard-eksekutif/",
        executive_dashboard_views.executive_dashboard,
        name="executive-dashboard",
    ),
    path(
        "crawler-artikel/",
        views.crawler_list,
        name="crawler-list",
    ),
    path(
        "crawler-artikel/jalankan/",
        views.crawler_run,
        name="crawler-run",
    ),
    path(
        "crawler-artikel/koleksi-terpadu/jalankan/",
        views.crawler_unified_run,
        name="crawler-unified-run",
    ),
    path(
        "crawler-artikel/sesi/<uuid:session_id>/",
        views.crawler_session_detail,
        name="crawler-session-detail",
    ),
    path(
        "crawler-artikel/status/",
        views.crawler_status,
        name="crawler-status",
    ),
    path(
        "crawler-artikel/ringkasan-status/",
        views.crawler_summary_status,
        name="crawler-summary-status",
    ),
    path(
        "crawler-artikel/google-news/",
        views.google_news_discovery_settings,
        name="google-news-discovery-settings",
    ),
    path(
        "crawler-artikel/job/<uuid:job_id>/",
        views.crawler_job_detail,
        name="crawler-job-detail",
    ),
    path(
        "crawler-artikel/job/<uuid:job_id>/batalkan/",
        views.crawler_job_cancel,
        name="crawler-job-cancel",
    ),
    path(
        "sumber-osint/",
        views.source_list,
        name="source-list",
    ),
    path(
        "sumber-osint/verifikasi/",
        views.source_verification_queue,
        name="source-verification-queue",
    ),
    path(
        "sumber-osint/verifikasi/<int:source_id>/tandai/",
        views.source_verification_mark_reviewed,
        name="source-verification-mark-reviewed",
    ),
    path(
        "sumber-osint/<int:source_id>/",
        views.source_detail,
        name="source-detail",
    ),
    path(
        "sumber-osint/tambah/",
        views.source_create,
        name="source-create",
    ),
    path(
        "sumber-osint/<int:source_id>/edit/",
        views.source_update,
        name="source-update",
    ),
    path(
        "sumber-osint/<int:source_id>/url-awal/tambah/",
        views.source_seed_create,
        name="source-seed-create",
    ),
    path(
        (
            "sumber-osint/<int:source_id>/url-awal/"
            "<uuid:seed_id>/edit/"
        ),
        views.source_seed_update,
        name="source-seed-update",
    ),
    path(
        "sumber-osint/<int:source_id>/discovery/tambah/",
        views.source_discovery_query_create,
        name="source-discovery-query-create",
    ),
    path(
        (
            "sumber-osint/<int:source_id>/discovery/"
            "<uuid:query_id>/edit/"
        ),
        views.source_discovery_query_update,
        name="source-discovery-query-update",
    ),
    path(
        "crawler-artikel/google-news/configurasi/",
        views.google_news_discovery_configure,
        name="google-news-discovery-configure",
    ),
    path(
        "sumber-osint/<int:source_id>/pola-url/tambah/",
        views.source_pattern_create,
        name="source-pattern-create",
    ),
    path(
        (
            "sumber-osint/<int:source_id>/pola-url/"
            "<uuid:pattern_id>/edit/"
        ),
        views.source_pattern_update,
        name="source-pattern-update",
    ),
    path(
        "geocoding-lokasi/",
        views.location_list,
        name="location-list",
    ),
    path(
        "peta-sebaran/",
        views.spread_map,
        name="spread-map",
    ),
    path(
        "peta-sebaran/data/",
        views.spread_map_data,
        name="spread-map-data",
    ),
    path(
        "geocoding-lokasi/<uuid:location_id>/",
        views.location_detail,
        name="location-detail",
    ),
    path(
        "laporan-arsip/",
        views.report_archive,
        name="report-archive",
    ),
    path(
        "laporan-arsip/ekspor/",
        views.report_archive_export,
        name="report-archive-export",
    ),
    path(
        "laporan-arsip/ekspor-pdf/",
        views.report_archive_export_pdf,
        name="report-archive-export-pdf",
    ),
    path(
        "laporan-arsip/ringkasan/",
        views.periodic_summary,
        name="periodic-summary",
    ),
    path(
        "ekstraksi-entitas/",
        views.entity_extraction_dashboard,
        name="entity-extraction",
    ),
    path(
        "ekstraksi-entitas/jalankan/",
        views.entity_extraction_run,
        name="entity-extraction-run",
    ),
    path(
        "ekstraksi-entitas/<uuid:article_id>/",
        views.article_extraction_detail,
        name="article-extraction-detail",
    ),
    path(
        "assessment-ancaman/skor-nasional/",
        views.national_risk_dashboard,
        name="national-risk-dashboard",
    ),
    path(
        "rekomendasi/per-wilayah/",
        views.recommendation_regional_dashboard,
        name="recommendation-regional-dashboard",
    ),
    path(
        "laporan-dokumen/",
        report_views.report_document_list,
        name="report-document-list",
    ),
    path(
        "laporan-dokumen/buat/",
        report_views.report_document_create,
        name="report-document-create",
    ),
    path(
        "laporan-dokumen/<uuid:report_id>/",
        report_views.report_document_edit,
        name="report-document-edit",
    ),
    path(
        "laporan-dokumen/<uuid:report_id>/ekspor-pdf/",
        report_views.report_document_export_pdf,
        name="report-document-export-pdf",
    ),
]
