# Generated by Django 5.2.16 on 2026-07-28 08:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama utama penyakit dalam Bahasa Indonesia.', max_length=200, unique=True)),
                ('canonical_name', models.CharField(blank=True, help_text='Nama baku atau nama internasional penyakit.', max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_priority', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_priority', 'is_active'], name='disease_priority_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Kode wilayah resmi jika tersedia.', max_length=50)),
                ('administrative_level', models.CharField(choices=[('country', 'Negara'), ('province', 'Provinsi'), ('regency', 'Kabupaten'), ('city', 'Kota'), ('district', 'Kecamatan'), ('village', 'Desa/Kelurahan'), ('other', 'Lainnya')], db_index=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country_code', models.CharField(default='ID', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='entities.location')),
            ],
            options={
                'ordering': ['administrative_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mention_text', models.CharField(blank=True, max_length=300)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('extraction_method', models.CharField(choices=[('system', 'Sistem'), ('rule_based', 'Rule-Based'), ('model', 'Model NLP'), ('manual', 'Input Manual')], default='system', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('unreviewed', 'Belum Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak')], db_index=True, default='unreviewed', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_locations', to='articles.article')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_article_locations', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_mentions', to='entities.location')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('case_count', models.PositiveIntegerField(blank=True, null=True)),
                ('death_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recovery_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hospitalized_count', models.PositiveIntegerField(blank=True, null=True)),
                ('trend', models.CharField(choices=[('increasing', 'Meningkat'), ('decreasing', 'Menurun'), ('stable', 'Stabil'), ('new_occurrence', 'Kejadian Baru'), ('spreading', 'Meluas'), ('unknown', 'Belum Diketahui')], db_index=True, default='unknown', max_length=30)),
                ('affected_group', models.CharField(blank=True, max_length=255)),
                ('government_response', models.TextField(blank=True)),
                ('fact_text', models.TextField(blank=True, help_text='Potongan teks artikel yang mendukung fakta.')),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('extraction_method', models.CharField(choices=[('system', 'Sistem'), ('rule_based', 'Rule-Based'), ('model', 'Model NLP'), ('manual', 'Input Manual')], default='system', max_length=20)),
                ('validation_status', models.CharField(choices=[('unreviewed', 'Belum Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak')], db_index=True, default='unreviewed', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='articles.article')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_article_facts', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_facts', to='entities.disease')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_facts', to='entities.location')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mention_text', models.CharField(blank=True, max_length=300)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('extraction_method', models.CharField(choices=[('system', 'Sistem'), ('rule_based', 'Rule-Based'), ('model', 'Model NLP'), ('manual', 'Input Manual')], default='system', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('unreviewed', 'Belum Ditinjau'), ('validated', 'Tervalidasi'), ('corrected', 'Dikoreksi'), ('rejected', 'Ditolak')], db_index=True, default='unreviewed', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_diseases', to='articles.article')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_article_diseases', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_mentions', to='entities.disease')),
            ],
            options={
                'indexes': [models.Index(fields=['disease', 'validation_status'], name='artdis_disease_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'disease'), name='unique_article_disease')],
            },
        ),
        migrations.CreateModel(
            name='DiseaseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('language', models.CharField(default='id', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='entities.disease')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('disease', 'alias'), name='unique_disease_alias')],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['administrative_level', 'name'], name='location_level_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'administrative_level', 'parent', 'country_code'), name='unique_location_hierarchy'),
        ),
        migrations.AddIndex(
            model_name='articlelocation',
            index=models.Index(fields=['location', 'validation_status'], name='artloc_location_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlelocation',
            constraint=models.UniqueConstraint(fields=('article', 'location'), name='unique_article_location'),
        ),
        migrations.AddIndex(
            model_name='articlefact',
            index=models.Index(fields=['disease', 'location', 'event_date'], name='artfact_dis_loc_date_idx'),
        ),
        migrations.AddIndex(
            model_name='articlefact',
            index=models.Index(fields=['validation_status', 'trend'], name='artfact_status_trend_idx'),
        ),
    ]
