# Generated by Django 5.2.16 on 2026-07-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('language', models.CharField(default='id', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='entities.location')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('location', 'alias'), name='unique_location_alias')],
            },
        ),
    ]
