# Generated by Django 5.2.16 on 2026-07-28 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_locationalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articledisease',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlefact',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlelocation',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ExtractionReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('article_disease', 'Penyakit Artikel'), ('article_location', 'Lokasi Artikel'), ('article_fact', 'Fakta Artikel')], db_index=True, max_length=30)),
                ('object_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('validate', 'Validasi'), ('correct', 'Koreksi'), ('reject', 'Penolakan')], db_index=True, max_length=20)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_extraction_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id', 'reviewed_at'], name='extract_review_object_idx'), models.Index(fields=['reviewer', 'reviewed_at'], name='extract_review_user_idx')],
            },
        ),
    ]
