# Generated by Django 5.2.16 on 2026-07-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_articledisease_validation_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Tandai jika gejala merupakan gejala utama dalam aturan surveilans.')),
                ('weight', models.FloatField(default=1.0)),
                ('source_reference', models.CharField(blank=True, help_text='Nama pedoman, regulasi, atau dokumen rujukan.', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_symptoms', to='entities.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_links', to='entities.symptom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('disease', 'symptom'), name='unique_disease_symptom')],
            },
        ),
        migrations.CreateModel(
            name='SymptomAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='entities.symptom')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('symptom', 'alias'), name='unique_symptom_alias')],
            },
        ),
    ]
