# Generated by Django 5.2.16 on 2026-07-29 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_symptom_diseasesymptom_symptomalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('legal_basis', models.CharField(blank=True, help_text='Dasar hukum atau pedoman yang menjadi rujukan program surveilans.', max_length=500)),
                ('document_number', models.CharField(blank=True, max_length=200)),
                ('document_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('historical', 'Historis'), ('draft', 'Draf')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-document_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_name', models.CharField(blank=True, help_text='Nama penyakit sebagaimana tercantum dalam dokumen rujukan.', max_length=255)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveillance_memberships', to='entities.disease')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_diseases', to='entities.surveillanceprogram')),
            ],
            options={
                'ordering': ['category', 'official_name'],
                'indexes': [models.Index(fields=['program', 'is_active'], name='survdis_program_active_idx'), models.Index(fields=['disease', 'is_active'], name='survdis_disease_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('program', 'disease'), name='unique_surveillance_program_disease')],
            },
        ),
    ]
